defaults:
  - pl_module/model: kleiner_tiny
  - pl_module/criterion: cross_entropy
  - pl_module/optimizer: adam
  - pl_module/scheduler: linear_warmup_cosine_decay
  - pl_module/transfer: default
  - data_module/dataset: dermamnist
  - data_module/augmentations: identity
  - trainer: default
  - logger: wandb
  - hydra/default
  - _self_ # necessary to be able to use ${task_name} in other configs


seed: 0
task_name: "image_classification"
device_name: "non-cuda"
create_data_summary: false
create_model_summary: false
